//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arama
    {
        public int AramaID { get; set; }
        public string AramaKelime { get; set; }
        public Nullable<int> AramaHit { get; set; }
        public Nullable<bool> AramaOnay { get; set; }
        public string AramaLink { get; set; }
        public string AramaBolum { get; set; }
        public Nullable<int> DilID { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
