//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArayanListesi
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Firma { get; set; }
        public string Tel { get; set; }
        public string CepTel { get; set; }
        public string Note { get; set; }
        public string MailDurum { get; set; }
        public Nullable<int> Ticket { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> KayitDurum { get; set; }
        public string Bolge { get; set; }
        public string StrTarih { get; set; }
    }
}
