//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariHareket
    {
        public int ChID { get; set; }
        public Nullable<System.DateTime> ChTarihi { get; set; }
        public Nullable<int> RefFirmaID { get; set; }
        public Nullable<int> ChAlinanOdeme { get; set; }
        public Nullable<int> ChSatisFiyati { get; set; }
        public string ChNot { get; set; }
        public string ChTuru { get; set; }
        public Nullable<int> RefSatisId { get; set; }
    
        public virtual Sati Sati { get; set; }
        public virtual Firma Firma { get; set; }
    }
}
