//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domain()
        {
            this.Isteklers = new HashSet<Istekler>();
            this.isKategoris = new HashSet<isKategori>();
            this.islers = new HashSet<isler>();
            this.Seos = new HashSet<Seo>();
            this.SiteKontrolDomainBirlestirs = new HashSet<SiteKontrolDomainBirlestir>();
            this.DomainNots = new HashSet<DomainNot>();
        }
    
        public int DomainID { get; set; }
        public string DomainAdi { get; set; }
        public int RefDomainFirmaID { get; set; }
        public Nullable<int> RefDomainKategori { get; set; }
        public Nullable<bool> DomainDurum { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> RefKayitliFirmaID { get; set; }
        public Nullable<int> RefHostingID { get; set; }
        public System.DateTime UzatmaTarihi { get; set; }
        public string IpAdres { get; set; }
        public Nullable<bool> Kontrol { get; set; }
        public Nullable<System.DateTime> SilmeTarihi { get; set; }
        public bool SilindimiAmazon { get; set; }
        public bool SilindimiHosting { get; set; }
        public bool SilindimiWebYoneticiAraclari { get; set; }
        public bool SilindimiGoogleBusiness { get; set; }
        public bool SilindimiYedekAlindimi { get; set; }
        public bool SilindimiVeriTabani { get; set; }
        public int RefDomainKayitliFirmaId { get; set; }
        public int DomainAksiyon { get; set; }
        public bool SatisOncelikli { get; set; }
        public bool GuncellemeSozlesmesiVarmi { get; set; }
        public bool OdemesiAlindi { get; set; }
        public string Note { get; set; }
    
        public virtual DomainKategori DomainKategori { get; set; }
        public virtual Hosting Hosting { get; set; }
        public virtual KayitliFirma KayitliFirma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Istekler> Isteklers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isKategori> isKategoris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isler> islers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seo> Seos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteKontrolDomainBirlestir> SiteKontrolDomainBirlestirs { get; set; }
        public virtual DomainKayitliFirma DomainKayitliFirma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomainNot> DomainNots { get; set; }
        public virtual Firma Firma { get; set; }
    }
}
