//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etiket
    {
        public int Id { get; set; }
        public string Kategori { get; set; }
        public string Text { get; set; }
        public int Sira { get; set; }
        public string Renk { get; set; }
        public string FontIcon { get; set; }
        public int Value { get; set; }
    }
}
