//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelinmeyenGun
    {
        public int GelinMeyenGunID { get; set; }
        public System.DateTime GelinmeyenGunTarihi { get; set; }
        public string GelinmeyenGunNedeni { get; set; }
        public string RefKullaniciID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
