//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GidilenMusteri
    {
        public int GidilenMusteriID { get; set; }
        public string GidilenMusteriFirmaAdi { get; set; }
        public string GidilenMusteriAdi { get; set; }
        public string GidilenMusteriSoyadi { get; set; }
        public string GidilenMusteriTelefon { get; set; }
        public string GidilenMusteriCepTelNo { get; set; }
        public string GidilenMusteriAdres { get; set; }
        public string GidilenMusteriMailAdres { get; set; }
        public string GidilenMusteriSehir { get; set; }
        public string GidilenMusteriilce { get; set; }
        public string GidilenMusteriWebAdresi { get; set; }
        public string GidilenMusteriKonu { get; set; }
        public Nullable<System.DateTime> GidilenMusteriTarih { get; set; }
        public string GidilenMusteriGorusenKullaniciID { get; set; }
        public Nullable<int> GidilenMusteriKonumID { get; set; }
        public Nullable<int> GidilenMusteriDomainKategoriID { get; set; }
        public Nullable<int> GidilenMusteriSektorID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DomainKategori DomainKategori { get; set; }
        public virtual Konum Konum { get; set; }
        public virtual Sektorler Sektorler { get; set; }
    }
}
