//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsiYapacakKisi
    {
        public int IsiYapacakKisiID { get; set; }
        public string RefIsiYapacakKisiUserID { get; set; }
        public int RefIsID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual isler isler { get; set; }
    }
}
