//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istekler
    {
        public int istekID { get; set; }
        public string istekAdi { get; set; }
        public string istekDetay { get; set; }
        public Nullable<int> istekRefFirmaID { get; set; }
        public Nullable<int> istekRefDomainID { get; set; }
        public Nullable<int> istekRefTipiID { get; set; }
        public string istekEkleyenKisiID { get; set; }
        public Nullable<System.DateTime> istekTarih { get; set; }
        public Nullable<bool> istekDurum { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
