//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class isYorum
    {
        public int isYorumID { get; set; }
        public string isYorumBaslik { get; set; }
        public string isYorumAciklama { get; set; }
        public Nullable<int> isYorumRefislerID { get; set; }
        public string isYorumRefYorumuYapanID { get; set; }
        public Nullable<System.DateTime> isYorumKayitTarih { get; set; }
        public Nullable<int> isYorumRefRandevuID { get; set; }
    
        public virtual isler isler { get; set; }
    }
}
