//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koordinat
    {
        public int KoordinatID { get; set; }
        public string KoordinatEnlem { get; set; }
        public string KoordinatBoylam { get; set; }
        public int RefFirmaID { get; set; }
    
        public virtual Firma Firma { get; set; }
    }
}
