//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailKontrol
    {
        public int MailKontrolID { get; set; }
        public string MailAdresi { get; set; }
        public string MailBaslik { get; set; }
        public Nullable<bool> MailOkundumu { get; set; }
        public Nullable<System.DateTime> MailGondermeTarihi { get; set; }
        public Nullable<System.DateTime> MailOkunmaTarihi { get; set; }
    }
}
