//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSablonu
    {
        public int MailSablonuID { get; set; }
        public string MailSablonuAdi { get; set; }
        public string MailSablonu1 { get; set; }
    }
}
