//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesaiCizelgesi
    {
        public int Id { get; set; }
        public System.DateTime Tarih { get; set; }
        public string GirisSaat { get; set; }
        public string CikisSaat { get; set; }
        public string MesaiSuresi { get; set; }
        public int Durum { get; set; }
        public string KullaniciId { get; set; }
    }
}
