//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeBildirimi
    {
        public int ObID { get; set; }
        public Nullable<System.DateTime> ObTarih { get; set; }
        public string ObNot { get; set; }
        public Nullable<int> RefFirmaID { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string ObKapanisNotu { get; set; }
        public Nullable<int> ObAlacak { get; set; }
    
        public virtual Firma Firma { get; set; }
    }
}
