//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeIsi
    {
        public int ProjeIsiID { get; set; }
        public int RefProjeID { get; set; }
        public string ProjeIsiAciklama { get; set; }
        public string RefEkleyenUserID { get; set; }
        public System.DateTime EklemeTarihi { get; set; }
        public string RefTamamlayanUserID { get; set; }
        public string RefKontrolEdenUserID { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<System.DateTime> KontrolTarihi { get; set; }
        public Nullable<int> RefProjeIsiID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Proje Proje { get; set; }
    }
}
