//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandevularView
    {
        public int RandevuID { get; set; }
        public string RandevuYeri { get; set; }
        public Nullable<System.DateTime> RandevuTarihi { get; set; }
        public string Bolge { get; set; }
        public string Firma { get; set; }
        public string Kiminle { get; set; }
        public Nullable<int> RandevuRefFirmaID { get; set; }
    }
}
