//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanalPos
    {
        public int id { get; set; }
        public int firmaID { get; set; }
        public string banka { get; set; }
        public string magaza { get; set; }
        public string kullaniciAdi { get; set; }
        public string sifre { get; set; }
        public string parola { get; set; }
    
        public virtual Firma Firma { get; set; }
    }
}
