//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisGorusme
    {
        public int Id { get; set; }
        public Nullable<int> RefDomainKategoriId { get; set; }
        public Nullable<int> RefFirmaId { get; set; }
        public Nullable<int> RefYetkiliId { get; set; }
        public string RefEkleyenKisiId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Note { get; set; }
        public Nullable<int> EtiketSatisGorusmeTypeId { get; set; }
    
        public virtual DomainKategori DomainKategori { get; set; }
        public virtual FirmaKisi FirmaKisi { get; set; }
        public virtual Firma Firma { get; set; }
    }
}
