//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sati()
        {
            this.Satis1 = new HashSet<Sati>();
        }
    
        public int SatisID { get; set; }
        public Nullable<int> musteriFirmaID { get; set; }
        public Nullable<int> musteridenAlinanOdeme { get; set; }
        public Nullable<int> musteriSatis { get; set; }
        public Nullable<int> araciFirmaID { get; set; }
        public Nullable<int> araciyaOdenen { get; set; }
        public Nullable<int> araciHakedis { get; set; }
        public string satisNot { get; set; }
        public Nullable<System.DateTime> satisTarihi { get; set; }
        public Nullable<int> refSatisID { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual Firma Firma1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sati> Satis1 { get; set; }
        public virtual Sati Sati1 { get; set; }
    }
}
