//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sifre
    {
        public int SifreID { get; set; }
        public string SifreWebSitesi { get; set; }
        public string SifreKullaniciAdi { get; set; }
        public string SifreSifre { get; set; }
        public string SifreGmail { get; set; }
        public string SifreGmailAdresi { get; set; }
        public string SifreUserID { get; set; }
        public string SifreDiger1 { get; set; }
        public string SifreDiger2 { get; set; }
        public string SifreDiger3 { get; set; }
        public string SifreDiger4 { get; set; }
        public string SifreDiger5 { get; set; }
        public string SifreDiger6 { get; set; }
    }
}
