//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteKontrolDomainBirlestir
    {
        public int SiteKontrolDomainBirlestirID { get; set; }
        public int RefDomainID { get; set; }
        public int RefSiteKontrolID { get; set; }
        public string RefUserID { get; set; }
        public System.DateTime SiteKontrolDomainBirlestirTarih { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Domain Domain { get; set; }
        public virtual SiteKontrol SiteKontrol { get; set; }
    }
}
