//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandartProjeIsleri
    {
        public int StandartProjeIsleriId { get; set; }
        public string RefStandartProjeIsleriYapacakKullaniciId { get; set; }
        public int StandartProjeIsleriSirasi { get; set; }
        public string StandartProjeIsleriIsAdi { get; set; }
        public Nullable<System.DateTime> StandartProjeIsleriTarih { get; set; }
        public string RefStandartProjeIsleriKontrolEdecekKullaniciId { get; set; }
        public string StandartProjeIsleriAciklama { get; set; }
        public string StandartProjeIsleriIdAnahtarIsmi { get; set; }
        public Nullable<bool> StandartProjeIsleriIdKontrol { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
