//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakvimAyar
    {
        public int TakvimAyarId { get; set; }
        public string RefUserId { get; set; }
        public string ApiTakvimId { get; set; }
        public string ApiKullaniciId { get; set; }
        public string ApiAdi { get; set; }
        public string ApiKimlikId { get; set; }
        public string ApiGuvenlikAnahtari { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
