//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeklifDetay
    {
        public int teklifDetayID { get; set; }
        public Nullable<System.DateTime> teklifDetayTarih { get; set; }
        public string teklifDetayAciklama { get; set; }
        public Nullable<int> teklifDetayRefTeklifID { get; set; }
        public string teklifDetayEkleyenKisi { get; set; }
        public Nullable<System.DateTime> teklifDetayDuzenlemeTarihi { get; set; }
        public Nullable<int> teklifDetayArayanID { get; set; }
    
        public virtual Arayanlar Arayanlar { get; set; }
        public virtual Teklif Teklif { get; set; }
    }
}
