//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teklif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teklif()
        {
            this.TeklifDetays = new HashSet<TeklifDetay>();
        }
    
        public int teklifID { get; set; }
        public Nullable<int> teklifRefArayanID { get; set; }
        public Nullable<int> teklifRefFirmaID { get; set; }
        public Nullable<int> teklifTuruID { get; set; }
        public Nullable<int> teklifSonucID { get; set; }
        public string teklifSorumlusuKisiID { get; set; }
        public Nullable<System.DateTime> teklifTarih { get; set; }
        public string teklifEkleyenKisiID { get; set; }
        public string teklifReferansNo { get; set; }
        public Nullable<int> teklifGecerlilikSuresi { get; set; }
        public Nullable<System.DateTime> teklifDuzeltmeTarihi { get; set; }
        public Nullable<int> teklifFiyati { get; set; }
        public string teklifDosyaAdi { get; set; }
    
        public virtual TeklifSonuc TeklifSonuc { get; set; }
        public virtual TeklifTuru TeklifTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifDetay> TeklifDetays { get; set; }
        public virtual Firma Firma { get; set; }
        public virtual Arayanlar Arayanlar { get; set; }
    }
}
