//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeknikRapor
    {
        public int TeknikRaporID { get; set; }
        public int RefTeknikRaporIsID { get; set; }
        public int TeknikRaporDurum { get; set; }
        public long TeknikRaporZaman { get; set; }
        public System.DateTime TeknikRaporTarih { get; set; }
        public string RefTeknikRaporUserID { get; set; }
    
        public virtual isler isler { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
