//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;

    
    public partial class Toplanti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toplanti()
        {
            this.ToplantiyaKatilanlars = new HashSet<ToplantiyaKatilanlar>();
        }
    
        public int ToplantiId { get; set; }
        public string ToplandiAdi { get; set; }
        public string ToplantiDetayi { get; set; }
        public Nullable<System.DateTime> ToplantiTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToplantiyaKatilanlar> ToplantiyaKatilanlars { get; set; }
    }
}
