//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToplantiyaKatilanlar
    {
        public int ToplantiyaKatilanlarId { get; set; }
        public int RefToplantiId { get; set; }
        public string RefAspNetUsers { get; set; }
        public string ToplantiYorumu { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Toplanti Toplanti { get; set; }
    }
}
